# Generated by Django 3.1.5 on 2021-01-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='รหัสพนักงาน')),
                ('id_card_no', models.CharField(db_index=True, help_text='ตัวอย่าง 6-1234-12345-67-8', max_length=17, unique=True, verbose_name='รหัสประจำตัวประชาชน')),
                ('name', models.CharField(help_text='ตัวอย่างเช่น นาย สมชาย ขายเก่ง', max_length=256, verbose_name='ชื่อ-นามสกุล')),
                ('tel_no', models.CharField(max_length=12, verbose_name='เบอร์โทรติดต่อ')),
                ('tel_no_2', models.CharField(blank=True, max_length=12, verbose_name='เบอร์โทรสำรอง')),
                ('role', models.CharField(choices=[('1', 'พนักงานขาย'), ('2', 'พนักงานเก็บเงิน'), ('3', 'พนักงานตรวจสอบ'), ('9', 'อื่นๆ')], default='1', max_length=1, verbose_name='ตำแหน่งงาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการ')),
            ],
            options={
                'verbose_name': 'พนักงาน',
                'verbose_name_plural': 'พนักงาน',
            },
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(db_index=True, default=True, verbose_name='เป็นพนักงานประจำสายปัจจุบัน')),
                ('date_joined', models.DateField(blank=True, verbose_name='วันที่เข้าประจำสาย')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_employee.employee', verbose_name='พนักงาน')),
            ],
            options={
                'verbose_name': 'พนักงานประจำสาย',
                'verbose_name_plural': 'พนักงานประจำสาย',
            },
        ),
        migrations.CreateModel(
            name='WorkLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ชื่อสายเก็บเงิน')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='แสดงในระบบ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการ')),
                ('members', models.ManyToManyField(through='app_employee.MemberShip', to='app_employee.Employee', verbose_name='พนักงานในสาย')),
            ],
            options={
                'verbose_name': 'สายเก็บเงิน',
                'verbose_name_plural': 'สายเก็บเงิน',
            },
        ),
        migrations.CreateModel(
            name='WorkLineReport',
            fields=[
                ('work_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_employee.workline', verbose_name='สายเก็บเงิน')),
            ],
            options={
                'verbose_name': 'รายงานสายเก็บเงินพนักงาน',
                'verbose_name_plural': 'รายงานสายเก็บเงินพนักงาน',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='workline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_employee.workline', verbose_name='สายงาน'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_lines',
            field=models.ManyToManyField(through='app_employee.MemberShip', to='app_employee.WorkLine', verbose_name='สายเก็บเงิน'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('employee', 'workline')},
        ),
    ]
