# Generated by Django 3.1.4 on 2021-01-02 06:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'พนักงาน', 'verbose_name_plural': 'พนักงาน'},
        ),
        migrations.AlterModelOptions(
            name='workline',
            options={'verbose_name': 'สายงาน', 'verbose_name_plural': 'สายงาน'},
        ),
        migrations.AddField(
            model_name='employee',
            name='tel_no_2',
            field=models.CharField(blank=True, max_length=12, verbose_name='เบอร์โทรศัพท์ติดต่อ (สำรอง)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'พนักงานขาย'), ('2', 'พนักงานเก็บเงิน'), ('3', 'พนักงานตรวจสอบ'), ('9', 'อื่นๆ')], default='1', max_length=1, verbose_name='ตำแหน่งงาน'), size=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel_no',
            field=models.CharField(max_length=12, verbose_name='เบอร์โทรศัพท์ติดต่อ'),
        ),
    ]
