# Generated by Django 3.1.4 on 2021-01-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0002_auto_20210102_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('1', 'พนักงานขาย'), ('2', 'พนักงานเก็บเงิน'), ('3', 'พนักงานตรวจสอบ'), ('9', 'อื่นๆ')], default='1', max_length=1, verbose_name='ตำแหน่งงาน'),
        ),
    ]
