# Generated by Django 3.1.4 on 2021-01-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0003_auto_20210102_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(db_index=True, default=1234, max_length=30, unique=True, verbose_name='รหัสพนักงาน'),
            preserve_default=False,
        ),
    ]
