# Generated by Django 3.1.4 on 2021-01-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0004_employee_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'พนักงานประจำสาย', 'verbose_name_plural': 'พนักงานประจำสาย'},
        ),
        migrations.AddField(
            model_name='employee',
            name='members',
            field=models.ManyToManyField(through='app_employee.MemberShip', to='app_employee.WorkLine', verbose_name='สายงาน'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('employee', 'workline')},
        ),
    ]
