# Generated by Django 3.1.4 on 2021-01-02 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0005_auto_20210102_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLineReport',
            fields=[
                ('work_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_employee.workline', verbose_name='สายงาน')),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='members',
            new_name='work_lines',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_card_no',
            field=models.CharField(db_index=True, help_text='ตัวอย่าง 6-1234-12345-67-8', max_length=17, unique=True, verbose_name='รหัสประจำตัวประชาชน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel_no',
            field=models.CharField(max_length=12, verbose_name='เบอร์โทรติดต่อ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel_no_2',
            field=models.CharField(blank=True, max_length=12, verbose_name='เบอร์โทรสำรอง'),
        ),
    ]
