# Generated by Django 3.1.4 on 2021-01-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0006_auto_20210103_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workline',
            options={'verbose_name': 'สายเก็บเงิน', 'verbose_name_plural': 'สายเก็บเงิน'},
        ),
        migrations.AlterModelOptions(
            name='worklinereport',
            options={'verbose_name': 'รายงานสายเก็บเงินพนักงาน', 'verbose_name_plural': 'รายงานสายเก็บเงินพนักงาน'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='ตัวอย่างเช่น นาย สมชาย ขายเก่ง', max_length=256, verbose_name='ชื่อ-นามสกุล'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_lines',
            field=models.ManyToManyField(through='app_employee.MemberShip', to='app_employee.WorkLine', verbose_name='สายเก็บเงิน'),
        ),
        migrations.AlterField(
            model_name='workline',
            name='name',
            field=models.CharField(max_length=128, verbose_name='ชื่อสายเก็บเงิน'),
        ),
        migrations.AlterField(
            model_name='worklinereport',
            name='work_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_employee.workline', verbose_name='สายเก็บเงิน'),
        ),
    ]
