# Generated by Django 3.1.5 on 2021-01-31 20:45

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_employee', '0001_initial'),
        ('app_customers', '0001_initial'),
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='เลขที่สัญญา')),
                ('status', models.CharField(choices=[('1', '<span style="color:green; weight:bold;">เปิดบัญชีการผ่อน</span>'), ('0', 'ปิดบัญชีการผ่อน')], db_index=True, default='1', max_length=1, verbose_name='สถานะ')),
                ('sales_price', models.DecimalField(decimal_places=2, help_text='ตัวอย่างเช่น 1500.50 หรือ 100 เป็นต้น', max_digits=8, verbose_name='ราคาเช่าซื้อ (บาท)')),
                ('comm_rate', models.IntegerField(choices=[(4, '4%'), (6, '6%'), (8, '8%')], verbose_name='จ่ายคอมมิสชั่น')),
                ('down_rate', models.IntegerField(choices=[(100, '100%'), (75, '75%'), (50, '50%'), (0, '0%')], verbose_name='ดาวน์')),
                ('down_price', models.DecimalField(decimal_places=2, help_text='ตัวอย่างเช่น 1500.50 หรือ 100 เป็นต้น', max_digits=8, verbose_name='เงินดาวน์ (บาท)')),
                ('time_count', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], verbose_name='จำนวนงวด')),
                ('per_time_price', models.DecimalField(decimal_places=2, help_text='ตัวอย่างเช่น 1500.50 หรือ 100 เป็นต้น', max_digits=8, verbose_name='ค่างวด (บาท)')),
                ('day_to_pay', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default=10, verbose_name='นัดเก็บทุกวันที่')),
                ('date_start', models.DateField(verbose_name='วันที่ทำสัญญา')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดชำระ')),
                ('date_effective', models.DateField(verbose_name='วันนัดชำระงวดแรก')),
                ('date_close', models.DateField(blank=True, null=True, verbose_name='วันที่ปิดสัญญา')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auditor', to='app_employee.employee', verbose_name='พนักงานตรวจสอบ')),
                ('bondsman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bondsman', to='app_customers.customer', verbose_name='ผู้ค้ำ 1')),
                ('bondsman_co', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bondsman_co', to='app_customers.customer', verbose_name='ผู้ค้ำ 2')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer', to='app_customers.customer', verbose_name='ผู้ซื้อ')),
                ('customer_co', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_co', to='app_customers.customer', verbose_name='ผู้ซื้อ 2')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_products.productinfo', verbose_name='สินค้า')),
                ('product_stock', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product', chained_model_field='product', on_delete=django.db.models.deletion.RESTRICT, to='app_products.productstock', verbose_name='หมายเลขตัวเครื่อง')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seller', to='app_employee.employee', verbose_name='พนักงานขาย')),
            ],
            options={
                'verbose_name': 'สัญญาเช่าซื้อ',
                'verbose_name_plural': 'สัญญาเช่าซื้อ',
            },
        ),
        migrations.CreateModel(
            name='ReceiptBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='เล่มที่ใบเสร็จ')),
                ('book_group', models.CharField(blank=True, max_length=16, null=True, verbose_name='หมวด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
            ],
            options={
                'verbose_name': 'เล่มใบเสร็จ',
                'verbose_name_plural': 'เล่มใบเสร็จ',
            },
        ),
        migrations.CreateModel(
            name='ReceiptBookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='หมายเหตุ')),
                ('tr_from', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50')], default='01', max_length=2, verbose_name='ตั้งแต่เลขที่')),
                ('tr_to', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50')], default='50', max_length=2, verbose_name='ถึงเลขที่')),
                ('requested_at', models.DateField(blank=True, null=True, verbose_name='วันที่เบิก')),
                ('approved_at', models.DateField(blank=True, null=True, verbose_name='วันที่ทำรายการ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_approver', to='app_employee.employee', verbose_name='ผู้อนุมัติ')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app_contracts.receiptbook', verbose_name='เล่มใบเสร็จ')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_requester', to='app_employee.employee', verbose_name='ผู้เบิก')),
            ],
            options={
                'verbose_name': 'เบิกเล่มใบเสร็จ',
                'verbose_name_plural': 'เบิกเล่มใบเสร็จ',
            },
        ),
        migrations.CreateModel(
            name='ReceiptBookReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_group', models.CharField(blank=True, max_length=16, null=True, verbose_name='หมวด')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='หมายเหตุ')),
                ('book_no_from', models.PositiveIntegerField(verbose_name='ตั้งแต่เล่มที่')),
                ('book_no_to', models.PositiveIntegerField(verbose_name='ถึงเล่มที่')),
                ('received_at', models.DateField(blank=True, null=True, verbose_name='วันที่รับ')),
                ('approved_at', models.DateField(blank=True, null=True, verbose_name='วันที่รับรอง')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_receive_approver', to='app_employee.employee', verbose_name='ผู้รับรอง')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_receiver', to='app_employee.employee', verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'รับเล่มใบเสร็จ',
                'verbose_name_plural': 'รับเล่มใบเสร็จ',
            },
        ),
        migrations.CreateModel(
            name='ReceiptBookActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='เลขที่รายการ')),
                ('type', models.CharField(choices=[('pa', 'รับชำระ[ขายเช่าซื้อ]'), ('cp', 'ยกเลิกการรับชำระ'), ('un', 'ยกเลิกการใช้ใบเสร็จ')], db_index=True, max_length=2, verbose_name='ประเภทการใช้')),
                ('receipt_no', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50')], default='01', max_length=2, verbose_name='เลขที่ใบเสร็จ')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='ตัวอย่างเช่น 1500.50 หรือ 100 เป็นต้น', max_digits=8, null=True, verbose_name='จำนวนเงินตามใบเสร็จ (บาท)')),
                ('date_use', models.DateField(verbose_name='วันที่ใช้ใบเสร็จ')),
                ('date_approve', models.DateField(blank=True, null=True, verbose_name='วันที่รับรอง')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่บันทึก')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contracts.contract', verbose_name='สัญญาเช่าซื้อ')),
                ('customer', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='contract', chained_model_field='customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_customers.customer', verbose_name='ลูกค้า')),
                ('receipt_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='activity_receipt_approve', to='app_employee.employee', verbose_name='ผู้รับรอง')),
                ('receipt_book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_contracts.receiptbook', verbose_name='เล่มที่ใบเสร็จ')),
                ('receipt_book_requester', smart_selects.db_fields.ChainedForeignKey(chained_field='receipt_book', chained_model_field='receipt_requester', on_delete=django.db.models.deletion.RESTRICT, related_name='activity_receipt_request', to='app_employee.employee', verbose_name='ผู้เบิกใบเสร็จ')),
                ('receipt_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='activity_receipt_use', to='app_employee.employee', verbose_name='ผู้ใช้ใบเสร็จ')),
            ],
            options={
                'verbose_name': 'รับชำระเงิน',
                'verbose_name_plural': 'รับชำระเงิน',
            },
        ),
        migrations.AddField(
            model_name='receiptbook',
            name='book_receiving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contracts.receiptbookreceive', verbose_name='รับใบเสร็จ'),
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_month', models.CharField(choices=[('6401', 'มกราคม 2564'), ('6402', 'กุมภาพันธ์ 2564'), ('6403', 'มีนาคม 2564'), ('6404', 'เมษายน 2564'), ('6405', 'พฤษภาคม 2564'), ('6406', 'มิถุนายน 2564'), ('6407', 'กรกฎาคม 2564'), ('6408', 'สิงหาคม 2564'), ('6409', 'กันยายน 2564'), ('6410', 'ตุลาคม 2564'), ('6411', 'พฤศจิกายน 2564'), ('6412', 'ธันวาคม 2564')], max_length=4, verbose_name='ประจำเดือน')),
                ('payment_type', models.CharField(choices=[('1', 'ปกติ'), ('2', 'เกินกำหนด')], default='1', max_length=1, verbose_name='ประเภท')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contracts.contract', verbose_name='สัญญา')),
            ],
            options={
                'verbose_name': 'งวดชำระประจำเดือน',
                'verbose_name_plural': 'งวดชำระประจำเดือน',
            },
        ),
    ]
