# Generated by Django 3.1.4 on 2021-01-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_employee', '0007_auto_20210103_1125'),
        ('app_products', '0007_auto_20210114_1851'),
        ('app_customers', '0003_auto_20210102_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(db_index=True, editable=False, max_length=30, unique=True, verbose_name='เลขที่สัญญา')),
                ('day_to_pay', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default=10, verbose_name='วันที่นัดเก็บ')),
                ('date_start', models.DateField(verbose_name='วันที่ทำสัญญา')),
                ('date_end', models.DateField(verbose_name='วันที่ครบกำหนดชำระ')),
                ('date_effective', models.DateField(verbose_name='วันนัดชำระงวดแรก')),
                ('date_close', models.DateField(verbose_name='วันที่ปิดสัญญา')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='auditor', to='app_employee.employee', verbose_name='พนักงานตรวจสอบ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer', to='app_customers.customer', verbose_name='ผู้ซื้อ')),
                ('customer_co', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_co', to='app_customers.customer', verbose_name='ผู้ซื้อ 2')),
                ('product_stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_products.productstock', verbose_name='สินค้ารับเข้า')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seller', to='app_employee.employee', verbose_name='พนักงานขาย')),
            ],
        ),
    ]
