# Generated by Django 3.1.4 on 2021-01-16 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0003_auto_20210102_1217'),
        ('app_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'สัญญาเช่าซื้อ', 'verbose_name_plural': 'สัญญาเช่าซื้อ'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_co',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_co', to='app_customers.customer', verbose_name='ผู้ซื้อ 2'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_close',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ปิดสัญญา'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ครบกำหนดชำระ'),
        ),
    ]
