# Generated by Django 3.1.5 on 2021-01-31 21:01

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0001_initial'),
        ('app_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptbookactivity',
            name='receipt_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_contracts.receiptbookrequest', verbose_name='เล่มที่ใบเสร็จ'),
        ),
        migrations.AlterField(
            model_name='receiptbookactivity',
            name='receipt_book_requester',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='receipt_book', chained_model_field='receiptbookrequest', on_delete=django.db.models.deletion.RESTRICT, related_name='activity_receipt_request', to='app_employee.employee', verbose_name='ผู้เบิกใบเสร็จ'),
        ),
    ]
