# Generated by Django 3.1.5 on 2021-01-24 18:48

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
        ('app_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='comm_rate',
            field=models.IntegerField(choices=[('4%', 4), ('6%', 6), ('8%', 8)], default=4, verbose_name='คอมมิสชั่น'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='down_price',
            field=models.DecimalField(decimal_places=2, default=50, help_text='ตัวอย่างเช่น 1500.50 หรือ 100 เป็นต้น', max_digits=8, verbose_name='เงินดาวน์ (บาท)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='down_rate',
            field=models.IntegerField(choices=[('100%', 100), ('75%', 75), ('50%', 50), ('0%', 0)], default=50, verbose_name='ดาวน์'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='per_time_price',
            field=models.DecimalField(decimal_places=2, default=200, help_text='ตัวอย่างเช่น 1500.50 หรือ 100 เป็นต้น', max_digits=8, verbose_name='ค่างวด (บาท)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='ตัวอย่างเช่น 1500.50 หรือ 100 เป็นต้น', max_digits=8, verbose_name='ราคาเช่าซื้อ (บาท)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='time_count',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18), ('19', 19), ('20', 20), ('21', 21), ('22', 22), ('23', 23), ('24', 24)], default=20, verbose_name='จำนวนงวด'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='product_stock',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product', chained_model_field='product', on_delete=django.db.models.deletion.RESTRICT, to='app_products.productstock', verbose_name='หมายเลขตัวเครื่อง'),
        ),
    ]
