# Generated by Django 3.1.5 on 2021-02-01 18:57

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0001_initial'),
        ('app_contracts', '0002_auto_20210131_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptbookactivity',
            name='receipt_book_requester',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='receipt_book', chained_model_field='receipt_requester', on_delete=django.db.models.deletion.RESTRICT, related_name='activity_receipt_request', to='app_employee.employee', verbose_name='ผู้เบิกใบเสร็จ'),
        ),
    ]
