# Generated by Django 3.1.5 on 2021-01-24 19:18

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0001_initial'),
        ('app_contracts', '0003_auto_20210124_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='ตัวอย่างเช่น 1500.50 หรือ 100 เป็นต้น', max_digits=8, verbose_name='จำนวนเงิน (บาท)')),
                ('date_pay', models.DateField(verbose_name='วันที่ใช้ใบเสร็จ')),
                ('date_add', models.DateField(verbose_name='วันที่บันทึก')),
                ('date_approve', models.DateField(blank=True, null=True, verbose_name='วันที่รับรอง')),
                ('tr_no', models.CharField(default='01', max_length=2, verbose_name='ใบเสร็จ เลขที่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pay_approver', to='app_employee.employee', verbose_name='ผู้รับรอง')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pay_collector', to='app_employee.employee', verbose_name='พนักงานเก็บเงิน')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contracts.contract', verbose_name='สัญญาเช่าซื้อ')),
                ('for_month', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='contract', chained_model_field='contract', on_delete=django.db.models.deletion.CASCADE, to='app_contracts.monthlypayment', verbose_name='ประจำเดือน')),
                ('tr_book_no', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_contracts.receiptbook', verbose_name='ใบเสร็จ เล่มที่')),
            ],
            options={
                'verbose_name': 'รับชำระเงิน',
                'verbose_name_plural': 'รับชำระเงิน',
            },
        ),
    ]
