# Generated by Django 3.1.4 on 2021-01-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0003_auto_20210102_1217'),
        ('app_contracts', '0003_auto_20210117_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bondsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bondsman', to='app_customers.customer', verbose_name='ผู้ค้ำ 1'),
        ),
        migrations.AddField(
            model_name='contract',
            name='bondsman_co',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bondsman_co', to='app_customers.customer', verbose_name='ผู้ค้ำ 2'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('1', '<span style="color:green; weight:bold;">เปิดบัญชีการผ่อน</span>'), ('0', 'ปิดบัญชีการผ่อน')], db_index=True, default='1', max_length=1, verbose_name='สถานะ'),
        ),
    ]
