# Generated by Django 3.1.5 on 2021-01-26 20:27

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0002_auto_20210124_1848'),
        ('app_employee', '0001_initial'),
        ('app_contracts', '0004_actualpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualpay',
            name='customer',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='contract', chained_model_field='contract_set', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_customers.customer', verbose_name='ลูกค้า'),
        ),
        migrations.AlterField(
            model_name='actualpay',
            name='approver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': '3'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pay_approver', to='app_employee.employee', verbose_name='ผู้รับรอง'),
        ),
        migrations.AlterField(
            model_name='actualpay',
            name='collector',
            field=models.ForeignKey(limit_choices_to={'role': '2'}, on_delete=django.db.models.deletion.RESTRICT, related_name='pay_collector', to='app_employee.employee', verbose_name='พนักงานเก็บเงิน'),
        ),
    ]
