# Generated by Django 3.1.5 on 2021-01-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0001_initial'),
        ('app_contracts', '0006_auto_20210126_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptbookrequest',
            name='book_group',
        ),
        migrations.AddField(
            model_name='receiptbook',
            name='book_group',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='หมวด'),
        ),
        migrations.AlterField(
            model_name='receiptbookrequest',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app_contracts.receiptbook', verbose_name='เล่มใบเสร็จ'),
        ),
        migrations.CreateModel(
            name='ReceiptBookReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_group', models.CharField(blank=True, max_length=16, null=True, verbose_name='หมวด')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='หมายเหตุ')),
                ('book_no_from', models.PositiveIntegerField(verbose_name='ตั้งแต่เล่มที่')),
                ('book_no_to', models.PositiveIntegerField(verbose_name='ถึงเล่มที่')),
                ('received_at', models.DateField(blank=True, null=True, verbose_name='วันที่รับ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_receiver', to='app_employee.employee', verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'รับเล่มใบเสร็จ',
                'verbose_name_plural': 'รับเล่มใบเสร็จ',
            },
        ),
        migrations.AddField(
            model_name='receiptbook',
            name='book_receiving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contracts.receiptbookreceive', verbose_name=''),
        ),
    ]
