# Generated by Django 3.1.5 on 2021-01-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0001_initial'),
        ('app_contracts', '0007_auto_20210128_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptbookreceive',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_receive_approver', to='app_employee.employee', verbose_name='ผู้รับรอง'),
        ),
        migrations.AlterField(
            model_name='receiptbook',
            name='book_receiving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_contracts.receiptbookreceive', verbose_name='รับใบเสร็จ'),
        ),
        migrations.AlterField(
            model_name='receiptbookreceive',
            name='received_at',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่รับรอง'),
        ),
    ]
