# Generated by Django 3.1.5 on 2021-01-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ยี่ห้อ',
                'verbose_name_plural': 'ยี่ห้อ',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='รหัสสินค้า')),
                ('model', models.CharField(blank=True, help_text='รายการ / รุ่น', max_length=128, verbose_name='รุ่นสินค้า')),
                ('note', models.TextField(blank=True, verbose_name='รายละเอียด/หมายเหตุ')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='แสดงในระบบ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.productbrand', verbose_name='ยี่ห้อสินค้า')),
            ],
            options={
                'verbose_name': 'รหัสสินค้า',
                'verbose_name_plural': 'รหัสสินค้า',
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, help_text='หมายเลขเครื่อง', max_length=64, unique=True, verbose_name='S/N')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='ตัวอย่างเช่น 1500.50 หรือ 100 เป็นต้น', max_digits=8, verbose_name='ราคาต้นทุน (บาท)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_products.productinfo', verbose_name='รหัสสินค้า')),
            ],
            options={
                'verbose_name': 'รายการสินค้ารับเข้า',
                'verbose_name_plural': 'รายการสินค้ารับเข้า',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ประเภท')),
                ('category', models.CharField(choices=[('1', 'เครื่องใช้ไฟฟ้า'), ('2', 'แอร์/ตู้แช่')], db_index=True, default='1', max_length=1, verbose_name='กลุ่ม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ประเภท',
                'verbose_name_plural': 'ประเภท',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='ตัวอย่างเช่น ??', max_length=32, unique=True, verbose_name='เลขที่รับเข้า')),
                ('date', models.DateField(db_index=True, help_text='ตัวอย่างเช่น ??', verbose_name='วันที่รับเข้า')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
                ('items', models.ManyToManyField(through='app_products.ProductStock', to='app_products.ProductInfo', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รับเข้าสินค้า',
                'verbose_name_plural': 'รับเข้าสินค้า',
            },
        ),
        migrations.AddField(
            model_name='productstock',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_products.purchaseorder', verbose_name='เลขที่รับเข้า'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.producttype', verbose_name='ประเภทสินค้า'),
        ),
    ]
