# Generated by Django 3.1.4 on 2021-01-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_auto_20201223_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.CharField(choices=[('1', 'เครื่องใช้ไฟฟ้า'), ('2', 'แอร์/ตู้แช่')], db_index=True, default='1', max_length=1, verbose_name='กลุ่ม'),
        ),
    ]
