# Generated by Django 3.1.4 on 2021-01-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_producttype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='แสดงในระบบ'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='note',
            field=models.TextField(blank=True, verbose_name='รายละเอียด/หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการ'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ประเภท'),
        ),
    ]
