# Generated by Django 3.1.4 on 2021-01-03 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0005_auto_20210102_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, help_text='หมายเลขเครื่อง', max_length=64, unique=True, verbose_name='S/N')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='ตัวอย่างเช่น 1500.50 หรือ 100 เป็นต้น', max_digits=8, verbose_name='ราคาต้นทุน (บาท)')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
            },
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.productbrand', verbose_name='ยี่ห้อสินค้า'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='model',
            field=models.CharField(blank=True, help_text='รายการ / รุ่น', max_length=128, verbose_name='รุ่นสินค้า'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_products.producttype', verbose_name='ประเภทสินค้า'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='ตัวอย่างเช่น ??', max_length=32, unique=True, verbose_name='เลขที่รับเข้า')),
                ('date', models.DateField(db_index=True, help_text='ตัวอย่างเช่น ??', verbose_name='วันที่รับเข้า')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างรายการ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขรายการล่าสุด')),
                ('items', models.ManyToManyField(through='app_products.ProductStock', to='app_products.ProductInfo', verbose_name='สินค้า')),
            ],
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_products.productinfo', verbose_name='รหัสสินค้า'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_products.purchaseorder', verbose_name='เลขที่รับเข้า'),
        ),
    ]
