# Generated by Django 3.1.4 on 2021-01-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0006_auto_20210103_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name': 'รายการสินค้ารับเข้า', 'verbose_name_plural': 'รายการสินค้ารับเข้า'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'รับเข้าสินค้า', 'verbose_name_plural': 'รับเข้าสินค้า'},
        ),
    ]
