# Generated by Django 3.1.5 on 2021-01-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=256, verbose_name='บ้านเลขที่')),
                ('second_line', models.CharField(max_length=256, verbose_name='หมู่/ซอย/ถนน')),
                ('sub_district', models.CharField(max_length=64, verbose_name='ตำบล')),
                ('district', models.CharField(max_length=64, verbose_name='อำเภอ')),
                ('province', models.CharField(max_length=64, verbose_name='จังหวัด')),
            ],
            options={
                'verbose_name': 'ข้อมูลที่อยู่',
                'verbose_name_plural': 'ข้อมูลที่อยู่',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_no', models.CharField(db_index=True, help_text='x-xxxx-xxxxx-xx-x', max_length=17, unique=True)),
                ('title', models.CharField(choices=[('mr', 'นาย'), ('mrs', 'นาง'), ('miss', 'นางสาว')], max_length=4, verbose_name='title')),
                ('first_name', models.CharField(max_length=32, verbose_name='first name')),
                ('last_name', models.CharField(max_length=32, verbose_name='last name')),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('S', 'โสด'), ('M', 'สมรส'), ('D', 'หย่าร้าง'), ('W', 'หม้าย')], max_length=1, verbose_name='marital status')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_customers.customeraddress')),
            ],
            options={
                'verbose_name': 'ข้อมูลลูกค้า',
                'verbose_name_plural': 'ข้อมูลลูกค้า',
            },
        ),
    ]
