# Generated by Django 3.1.4 on 2020-12-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustermerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=256)),
                ('second_line', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_no', models.CharField(db_index=True, help_text='x-xxxx-xxxxx-xx-x', max_length=17, unique=True)),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'นาง'), ('miss', 'นางสาว')], max_length=4, verbose_name='title')),
                ('first_name', models.CharField(max_length=32, verbose_name='first name')),
                ('last_name', models.CharField(max_length=32, verbose_name='last name')),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
