# Generated by Django 3.1.4 on 2020-12-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=256, verbose_name='บ้านเลขที่')),
                ('second_line', models.CharField(max_length=256, verbose_name='หมู่/ซอย/ถนน')),
                ('sub_district', models.CharField(max_length=64, verbose_name='ตำบล')),
                ('district', models.CharField(max_length=64, verbose_name='อำเภอ')),
                ('province', models.CharField(max_length=64, verbose_name='จังหวัด')),
            ],
        ),
        migrations.DeleteModel(
            name='CustermerAddress',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'ข้อมูลลูกค้า', 'verbose_name_plural': 'ข้อมูลลูกค้า'},
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('S', 'โสด'), ('M', 'สมรส'), ('D', 'หย่าร้าง'), ('W', 'หม้าย')], default='S', max_length=1, verbose_name='marital status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='app_customers.customeraddress'),
            preserve_default=False,
        ),
    ]
