# Generated by Django 3.1.5 on 2021-01-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(verbose_name='วันเกิด'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_card_no',
            field=models.CharField(db_index=True, help_text='x-xxxx-xxxxx-xx-x', max_length=17, unique=True, verbose_name='เลขประจำตัวประชาชน'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(choices=[('S', 'โสด'), ('M', 'สมรส'), ('D', 'หย่าร้าง'), ('W', 'หม้าย')], max_length=1, verbose_name='สถานะสมรส'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(choices=[('mr', 'นาย'), ('mrs', 'นาง'), ('miss', 'นางสาว')], max_length=4, verbose_name='คำนำหน้า'),
        ),
    ]
