# Generated by Django 3.1.5 on 2021-02-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0002_auto_20210201_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='วันเกิด'),
        ),
    ]
