# Generated by Django 3.1.5 on 2021-02-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0003_auto_20210201_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='อาชีพ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='คู่สมรส'),
        ),
    ]
