# Generated by Django 3.1.5 on 2021-02-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0004_auto_20210201_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth_be',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='วัน/เดือน/ปี เกิด'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ชื่อ-นามสกุล คู่สมรส'),
        ),
    ]
